export class KnowledgeCentroAyuda {
  static ID = 'id';
  static PAGE = 'page';
  static SEARCH = 'q';
  static FAQS = 'faq';
  static ON = 'on';
  static ON_BIZ = 'biz';
  static ON_YOU = 'you';
  static YOU_DEBITO_CATEGORY = 'debito';
  static YOU_ABRIR_CUENTA_CATEGORY = 'abrir_cuenta';
  static YOU_TARJETA_FISICA_Y_VIRTUAL_CATEGORY = 'tarjeta_fisica_y_virtual';
  static YOU_VERIFICACION_CUENTA_CATEGORY = 'verificacion_cuenta';
  static YOU_CUENTA_NOMINA_CATEGORY = 'cuenta_nomina';
  static YOU_CREDITO_CATEGORY = 'credito';
  static YOU_TARJETA_CREDITO_CATEGORY = 'tarjeta_credito';
  static YOU_SOLICITUD_TARJETA_CREDITO_CATEGORY = 'solicitud_tarjeta_credito';
  static YOU_USO_TARJETA_CREDITO_CATEGORY = 'uso_tarjeta_credito';
  static YOU_PAGO_TARJETA_CREDITO_CATEGORY = 'pago_tarjeta_credito';
  static YOU_PAGOS_DIFERIDOS_CATEGORY = 'pagos_diferidos';
  static YOU_CREDITO_AUTO_CATEGORY = 'credito_auto';
  static YOU_CREDITO_NOMINA_CATEGORY = 'credito_nomina';
  static YOU_CREDITOS_PERSONALES_CATEGORY = 'creditos_personales';
  static YOU_INVERSIONES_CATEGORY = 'inversiones';
  static YOU_AHORRO_CATEGORY = 'ahorro';
  static YOU_APP_CATEGORY = 'app';
  static BIZ_DEBITO_CATEGORY = 'debito';
  static BIZ_CREDITO_CATEGORY = 'credito';
  static BIZ_TERMINALES_CATEGORY = 'terminales';
  static BIZ_SEGUROS_CATEGORY = 'seguros';


  public id: string;
  public answer: string;
  public article_case_attach_count: number;
  public article_created_by_id: string;
  public article_created_date: string;
  public article_number: string;
  public article_total_view_count: number;
  public chat_answer: string;
  public created_by_id: string;
  public created_date: string;
  public currency_iso_code: string;
  public first_published_date: string;
  public is_deleted: boolean;
  public is_latest_version: boolean;
  public is_master_language: boolean;
  public is_visible_in_app: boolean;
  public is_visible_in_csp: boolean;
  public is_visible_in_pkb: boolean;
  public is_visible_in_prm: boolean;
  public knowledge_article_id: string;
  public language: string;
  public last_modified_by_id: string;
  public last_modified_date: string;
  public last_published_date: string;
  public master_version_id: string;
  public owner_id: string;
  public publish_status: string;
  public question: string;
  public record_type_id: string;
  public source_id: string;
  public summary: string;
  public system_modstamp: string;
  public title: string;
  public url_name: string;
  public validation_status: string;
  public version_number: number;

  public clear() {
    this.id = 'string';
    this.answer = 'string';
    this.article_case_attach_count = 0;
    this.article_created_by_id = 'string';
    this.article_created_date = 'string';
    this.article_number = 'string';
    this.article_total_view_count = 0;
    this.chat_answer = 'string';
    this.created_by_id = 'string';
    this.created_date = 'string';
    this.currency_iso_code = 'string';
    this.first_published_date = 'string';
    this.is_deleted = false;
    this.is_latest_version = false;
    this.is_master_language = false;
    this.is_visible_in_app = false;
    this.is_visible_in_csp = false;
    this.is_visible_in_pkb = false;
    this.is_visible_in_prm = false;
    this.knowledge_article_id = 'string';
    this.language = 'string';
    this.last_modified_by_id = 'string';
    this.last_modified_date = 'string';
    this.last_published_date = 'string';
    this.master_version_id = 'string';
    this.owner_id = 'string';
    this.publish_status = 'string';
    this.question = 'string';
    this.record_type_id = 'string';
    this.source_id = null;
    this.summary = 'string';
    this.system_modstamp = 'string';
    this.title = 'string';
    this.url_name = 'string';
    this.validation_status = 'string';
    this.version_number = 0;
  }
}
